### ISSUE TITLE
Dejanos  tus comentarios aparece en forma de texto

### ISSUE THREAD

**Issue by facu-123** [CentroCatu/prueba_de_git#30]
El área de texto "Dejanos tu comentario " no se elimina al ingresar información.
Pasos para reproducir el bug:  Dirigirse a la sección de comentarios e ingresar comentarios

**Comment by maxileyba** [comment]
pues el bug de pagina de fede que tiene quitar codigo de seguridad no tiene nada que ver en pagina si no alguien puede hackear pero fede tu pagina es genial.

**Comment by maxileyba** [comment]
ya esta arreglado

**Comment by maxileyba** [comment]
esta la mejor el mundo.
